// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace SkyraGameplayTags
{
	SKYRAGAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Skyra will use
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	// TODO:这里的input考虑去掉
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);
	

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	SKYRAGAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	SKYRAGAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	//MovementComp里的，TODO:处理
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
	
	// 通用的一些表现效果
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_AnimationStyle);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_BodyStyle)
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PawnType_Player);
	
	// 考虑分模块
	// GameplayEffect
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageTrait_Instant);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageTrait_Periodic);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageType_Basic);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Heal_Instant);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Heal_Periodic);
	
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_StatusChange_Death);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_StatusChange_Spawning);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Pawn_DamageTaken);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Pawn_Death);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Pawn_Heal);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Pawn_Spawn);
	
	

	
	// 这个是射击特有的Tag,后面要考虑分模块从这里分走
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_MagazineFull);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_NoSpareAmmo);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_NoFiring);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Jump);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Dash);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Reload);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_WeaponFire);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Passive_AutoReload);
	
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Dash);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Reload);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_WeaponFire);
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_FireAuto);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ADS);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	
	//GameplayEffect.DamageType.Pistol
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageType_Example);
	// 这里按武器行为来定义，例如GameplayCue_Weapon_Example，example是武器，接下来的子标签定义了对应的GC
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Example_Impact);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Example_Fire);
	
	
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shooter_Weapon_MagazineAmmo);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shooter_Weapon_MagazineSize);
	SKYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shooter_Weapon_SpareAmmo);
	
	
	
	

};
